version: '3'
services:
  test_hub:
    image: selenium/hub:3.141.59
    shm_size: 2048
    environment:
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=900000
  test_chrome:
    image: selenium/node-chrome-debug:3.141.59
    shm_size: 1024M
    environment:
      - HUB_PORT_4444_TCP_ADDR=test_hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_ENV_no_proxy=localhost
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - no_proxy=localhost
    ports:
      - "5900:5900"
    entrypoint: >
      bash -c '
        SE_OPTS="-timeout 720 -browserTimeout 360" /opt/bin/entry_point.sh'
    depends_on:
      - test_hub
  tests_repo:
    image: statoilfuelretail/ev-selenium:latest
    user: "${UID}:${GID}"
    volumes:
      - ./:/opt/automation/
    entrypoint: ./run_tests.sh
    env_file: ./compose.env
    depends_on:
      - test_chrome
